project:
  type: book
  output-dir: docs

book:
  title: "2025년 하계 산업보건학회"
  author: "jinha"
  date: "2025. 8. 15."
  chapters:
    - index.qmd
    - intro.qmd
    - Dose_Response_Model.qmd
    - Dose_Response_Model_II.qmd
    - Dose_Response_Model_III.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

